# The following properties are required by all services
# Ansible connection properties
ssh_user: "{{ lookup('ansible.builtin.env', 'PODMAN_CD_USER') }}"
ssh_pass: "{{ lookup('ansible.builtin.env', 'PODMAN_CD_PASS') }}"
ansible_user: "{{ lookup('ansible.builtin.env', 'PODMAN_CD_USER') }}"
ansible_become_password: "{{ lookup('ansible.builtin.env', 'PODMAN_CD_PASS') }}"
ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

# General properties
pd_prop_project_name: "<%= projectNameUpperCase %>"
pd_prop_service_name: "<%= serviceName %>"
pd_prop_project_version: "{{ lookup('ansible.builtin.env', 'PODMAN_PROJECT_VERSION') }}"
pd_prop_artifact_name: "{{ lookup('ansible.builtin.env', 'PODMAN_ARTIFACT_NAME') }}"
pd_prop_artifact_sha256: "{{ lookup('ansible.builtin.env', 'PODMAN_ARTIFACT_SHA256') }}"
pd_prop_build_number: "{{ lookup('ansible.builtin.env', 'PODMAN_BUILD_NUMBER') }}"
pd_prop_project_version_run: "{{ pd_prop_project_version }}-{{ pd_prop_build_number }}"

# The following properties are custom to each particular service
context: <%= tomcatContext %>
<% if (altAppDirName) { -%>
alt_app_dir_name: <%= altAppDirName %>
<% } -%>

# By default, the Tomcat port is set dynamically by using the port_manager role
# If you need to set a static port, replace the dynamic port assignment value with your static value
tomcat_https_port: "{{ portmanager_assignments[ansible_host] }}"

# If you need to use a particular version of Tomcat, set the version here
tomcat_version_number: "8.5.51"
